image: Ubuntu2004  # образ для сборки

stack: jdk 11  # версия JDK

branches:
  only:
    - main  # ветка git

build: off  # будем использовать свой скрипт сборки

install:
  - sudo apt-get update
  - sudo apt-get install -y ca-certificates
  - sudo update-ca-certificates
  - java -version
  - java -jar ./artifacts/app-mbank.jar &
  - chmod +x gradlew

build_script:
  - ./gradlew test --info -Dhttps.protocols=TLSv1.2
